title: IdeUltra
description: A snappy, native, local-first code IDE.
theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jekyll-feed
url: https://mpjhorner.github.io
baseurl: /IdeUltra
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
